# Generated by Django 5.2.7 on 2025-10-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sender', models.CharField(choices=[('user', 'user'), ('bot', 'bot')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
