# Generated by Django 5.2.7 on 2025-10-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cancel', 'cancel'), ('status', 'status'), ('pets', 'pets'), ('seats', 'seats'), ('verify_pnr', 'verify_pnr')], max_length=30)),
                ('pnr', models.CharField(blank=True, max_length=20, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.booking')),
            ],
        ),
    ]
